runtime: python310
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
  secure: always
- url: .*
  script: main.app
  secure: always
- url: /static
  static_dir: static
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
