runtime: python310

handlers:
- url: /js
  static_dir: js
  secure: always
- url: .*
  script: main.app
  secure: always
- url: /static
  static_dir: static
  secure: always

includes:
  - env_variables.yaml
