application: home-poker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: /generated
  static_dir: generated
- url: /closure
  static_dir: closure-library/closure
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
